# Generated by Django 4.0.4 on 2022-05-19 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='productid',
            new_name='productId',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='userid',
            new_name='userId',
        ),
    ]
