# Generated by Django 4.0.4 on 2022-05-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0002_rename_productid_food_productid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='helpfulness',
            field=models.CharField(max_length=30),
        ),
    ]
