# Generated by Django 4.0.4 on 2022-05-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0003_alter_food_helpfulness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='helpfulness',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='food',
            name='productId',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='food',
            name='userId',
            field=models.CharField(max_length=100),
        ),
    ]
