# Generated by Django 4.0.4 on 2022-05-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0005_alter_food_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='productId',
            field=models.CharField(max_length=150),
        ),
    ]
