# Generated by Django 4.0.4 on 2022-05-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0006_alter_food_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='helpfulness',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='food',
            name='productId',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='food',
            name='userId',
            field=models.CharField(max_length=12),
        ),
    ]
