# Generated by Django 4.0.4 on 2022-05-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0007_alter_food_helpfulness_alter_food_productid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='userId',
            field=models.CharField(max_length=30),
        ),
    ]
