# Generated by Django 4.0.4 on 2022-05-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0009_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='score',
            field=models.FloatField(),
        ),
    ]
